FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win64"
RecentFilesList = ["src\\Entities\\InputManager.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Entity.bf", "src\\Entities\\Card.bf", "src\\Entities\\NumberCard.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\CollisionComponent.bf", "src\\BeefShenzenIOSolitaire.bf", "src\\CardManager.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\CameraComponent.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\GraphicsComponent.bf", "src\\Entities\\Entity.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\Sprite.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\Renderable.bf", "src\\Entities\\MouseInputManager.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\Math\\aabb2.bf", "src\\Entities\\Player.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\DearImGui\\ImGui.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\Input\\Buttons.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Collections\\List.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Systems\\src\\EntityManager.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Systems\\src\\EntityCommandBuffer.bf"]

[MainWindow]
X = 731
Y = 158
Width = 1189
Height = 892
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 297.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 0.045565
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1654.0
RequestedHeight = 627.0
SizePriority = 0.4658477
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 86.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Entity.bf"
CursorPos = 3199
VertPos = 2010.0
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "InputManager.bf"
TabWidth = 126.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\InputManager.bf"
CursorPos = 409
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "List.bf"
TabWidth = 64.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Collections\\List.bf"
CursorPos = 4743
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "EntityManager.bf"
TabWidth = 128.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Systems\\src\\EntityManager.bf"
CursorPos = 4243

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "EntityCommandBuffer.bf"
TabWidth = 169.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Systems\\src\\EntityCommandBuffer.bf"
CursorPos = 4114

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Release.bf"
TabWidth = 90.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\Release.bf"
CursorPos = 1294
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "System.bf"
TabWidth = 86.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\System.bf"
CursorPos = 2583
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SpecialCard.bf"
TabWidth = 114.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\SpecialCard.bf"
CursorPos = 140
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "NumberCard.bf"
TabWidth = 121.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\NumberCard.bf"
CursorPos = 146
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BeefShenzenIOSolitaire.bf"
TabWidth = 178.0
Type = "SourceViewPanel"
FilePath = "src\\BeefShenzenIOSolitaire.bf"
CursorPos = 1098
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CollisionComponent.bf"
TabWidth = 172.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\CollisionComponent.bf"
CursorPos = 229
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CardManager.bf"
TabWidth = 125.0
Type = "SourceViewPanel"
FilePath = "src\\CardManager.bf"
CursorPos = 2205
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SpecialButton.bf"
TabWidth = 123.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\SpecialButton.bf"
CursorPos = 42
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Background.bf"
TabWidth = 114.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Background.bf"
CursorPos = 56
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Player.bf"
TabWidth = 79.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Player.bf"
CursorPos = 96
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1488.0
RequestedHeight = 875.0
SizePriority = 0.4885873
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Sprite.bf"
TabWidth = 89.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\Sprite.bf"
CursorPos = 37
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Renderable.bf"
TabWidth = 122.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\Renderable.bf"
CursorPos = 224
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CameraComponent.bf"
TabWidth = 168.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\CameraComponent.bf"
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GraphicsComponent.bf"
TabWidth = 174.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Components\\GraphicsComponent.bf"
CursorPos = 71
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Entity.bf"
CursorPos = 31
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "aabb2.bf"
TabWidth = 82.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\Math\\aabb2.bf"
CursorPos = 11221
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImGui.bf"
TabWidth = 78.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\DearImGui\\ImGui.bf"
CursorPos = 134559
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Buttons.bf"
TabWidth = 88.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\Input\\Buttons.bf"
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Card.bf"
TabWidth = 73.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Card.bf"
CursorPos = 1165
VertPos = 481.5865
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 403.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.132951
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 270.0

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.867049
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[Breakpoints]]
File = "src\\Entities\\InputManager.bf"
Line = 26
Column = 5

[[Breakpoints]]
File = "src\\Entities\\InputManager.bf"
Line = 20
Column = 5
