FileVersion = 1
Dependencies = {corlib = "*", "Atma.Common" = "*", "Atma.Entities" = "*"}

[Project]
Name = "BeefShenzenIOSolitaire"
StartupObject = "BeefShenzenIOSolitaire.Program"

[Configs.Release.Win64]
BeefLibType = "Dynamic"
