FileVersion = 1
Projects = {BeefShenzenIOSolitaire = {Path = "."}, "Atma.Common" = {Path = "../../Source/Atma.Framework/src/Atma.Common"}, "Atma.Entities" = {Path = "../../Source/Atma.Framework/src/Atma.Entities"}}

[Workspace]
StartupProject = "BeefShenzenIOSolitaire"
