FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Entities\\InputManager.bf", "src\\Entities\\Card.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Sorting.bf", "src\\CardManager.bf", "src\\Entities\\Components\\CollisionComponent.bf", "src\\Entities\\Column.bf", "src\\Entities\\Entity.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\Math\\vec2\\float2.cs", "src\\BeefShenzenIOSolitaire.bf", "src\\Entities\\CardHolder.bf", "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Game.bf", "Disassembly", "Disassembly", "src\\Entities\\Background.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Random.bf", "Disassembly"]

[MainWindow]
X = 62
Y = 0
Width = 1713
Height = 1086
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 517.0
SizePriority = 250.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 627.0
SizePriority = 627.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 263.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1488.0
RequestedHeight = 875.0
SizePriority = 1488.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Sorting.bf"
TabWidth = 87.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Sorting.bf"
CursorPos = 290
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CollisionComponent.bf"
TabWidth = 162.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Components\\CollisionComponent.bf"
CursorPos = 339
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "float2.cs"
TabWidth = 78.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Common\\src\\Math\\vec2\\float2.cs"
CursorPos = 75558
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Entity.bf"
CursorPos = 860
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Card.bf"
TabWidth = 73.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Card.bf"
CursorPos = 1943
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CardHolder.bf"
TabWidth = 112.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\CardHolder.bf"
CursorPos = 342
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Game.bf"
TabWidth = 79.0
Type = "SourceViewPanel"
FilePath = "d:\\Source\\Atma.Framework\\src\\Atma.Entities\\src\\Game.bf"
CursorPos = 336
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Column.bf"
TabWidth = 89.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Column.bf"
CursorPos = 675
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BeefShenzenIOSolitaire.bf"
TabWidth = 178.0
Type = "SourceViewPanel"
FilePath = "src\\BeefShenzenIOSolitaire.bf"
CursorPos = 1181
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Background.bf"
TabWidth = 114.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\Background.bf"
CursorPos = 174
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CardManager.bf"
TabWidth = 125.0
Type = "SourceViewPanel"
FilePath = "src\\CardManager.bf"
CursorPos = 2880
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "InputManager.bf"
TabWidth = 126.0
Type = "SourceViewPanel"
FilePath = "src\\Entities\\InputManager.bf"
CursorPos = 2815
VertPos = 1508.0
ProjectName = "BeefShenzenIOSolitaire"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 560.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 278.0}, {Width = 268.0}, {Width = 200.0}]
Items = ["card_info", "this.card_name", "cards", "card_back", "sorted_cards", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 270.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"
